import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  RotateCcw,
  ArrowRight,
  TrendingUp,
  TrendingDown,
  HelpCircle,
  Lightbulb,
  AlertTriangle,
  Zap,
  CheckCircle2,
  XCircle,
  Share2,
  Sliders,
} from 'lucide-react';
import { useSessionStore } from '../../store/sessionStore';
import { useDiscoveryStore } from '../../store/discoveryStore';
import { useReviewStore } from '../../store/reviewStore';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { ScoreRing } from '../../components/ui/ScoreRing';
import { EmptyState } from '../../components/shared/States';
import './DebriefPage.css';

const MetricBar: React.FC<{ label: string; score: number; isInverse?: boolean }> = ({
  label,
  score,
  isInverse,
}) => {
  const color = isInverse
    ? score === 0
      ? 'var(--status-success)'
      : score <= 2
      ? 'var(--status-warning)'
      : 'var(--status-danger)'
    : score >= 80
    ? 'var(--status-success)'
    : score >= 60
    ? 'var(--brand-primary)'
    : score >= 40
    ? 'var(--status-warning)'
    : 'var(--status-danger)';

  const displayValue = isInverse ? `${score} detected` : `${score}%`;
  const fillWidth = isInverse ? `${Math.min(100, score * 30)}%` : `${score}%`;

  return (
    <div className="metric-bar">
      <div className="metric-bar__header">
        <span className="metric-bar__label">{label}</span>
        <span className="metric-bar__value" style={{ color }}>
          {displayValue}
        </span>
      </div>
      <div className="metric-bar__track">
        <div
          className="metric-bar__fill"
          style={{ width: fillWidth, background: color }}
        />
      </div>
    </div>
  );
};

export const DiscoveryDebriefPage: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const { getSessionById } = useSessionStore();
  const { getReviewBySessionId } = useReviewStore();
  const { setDifficulty, setPersona, goToStep } = useDiscoveryStore();
  const [showRetryModal, setShowRetryModal] = useState(false);
  const [showDiffModal, setShowDiffModal] = useState(false);

  const session = id ? getSessionById(id) : undefined;
  const review = session ? getReviewBySessionId(session.id) : undefined;

  // Use human-reviewed evaluation if reviewed, fallback to session debrief
  const debrief = (review && (review.reviewStatus === 'EDITED' || review.reviewStatus === 'ACCEPTED'))
    ? review.finalEvaluation
    : session?.debrief;

  if (!session || !debrief) {
    return (
      <div className="debrief-page">
        <EmptyState
          title="Session report not found"
          description="This session may not have completed its evaluation yet, or the session ID is invalid."
          action={{ label: 'Back to sessions', onClick: () => navigate('/sessions') }}
        />
      </div>
    );
  }

  const {
    score,
    strongMoments = [],
    weakMoments = [],
    missedQuestions = [],
    leadingQuestionFlags = [],
    prematurePitchFlags = [],
    questionsToAsk = [],
    improvements = [],
    strongestMoment,
    weakestMoment,
    recommendedNextStep,
    summary,
  } = debrief;

  const handleRetrySame = () => {
    navigate('/discovery/new');
  };

  const handleRetryHarder = () => {
    setDifficulty('hard');
    goToStep(4);
    navigate('/discovery/new');
  };

  const handleSwitchPersona = () => {
    goToStep(3);
    navigate('/discovery/new');
  };

  return (
    <div className="debrief-page">
      <div className="debrief-page__inner">
        {/* Human Review Status Banner */}
        {review && (
          <div className={`debrief-review-banner debrief-review-banner--${review.reviewStatus.toLowerCase()} animate-fade-in`}>
            <div className="debrief-review-banner__left">
              {review.reviewStatus === 'PENDING' && (
                <>
                  <Badge variant="default" size="sm">AI DIAGNOSIS — AWAITING HUMAN REVIEW</Badge>
                  <p>This report was generated by AI and is currently pending verification by a venture coach.</p>
                </>
              )}
              {review.reviewStatus === 'ACCEPTED' && (
                <>
                  <Badge variant="success" size="sm">HUMAN REVIEWED — AI EVALUATION ACCEPTED</Badge>
                  <p>Verified against transcript evidence by <strong>{review.reviewerName}</strong>.</p>
                </>
              )}
              {review.reviewStatus === 'EDITED' && (
                <>
                  <Badge variant="warning" size="sm">HUMAN REVIEWED — EVALUATION EDITED</Badge>
                  <p>
                    Original AI score was <strong>{review.originalEvaluation.score.overall}</strong>. Adjusted to <strong>{review.finalEvaluation.score.overall}</strong> by <strong>{review.reviewerName}</strong>.
                  </p>
                </>
              )}
              {review.reviewStatus === 'REJECTED' && (
                <>
                  <Badge variant="danger" size="sm">AI EVALUATION REJECTED</Badge>
                  <p>
                    Rejected by <strong>{review.reviewerName}</strong>: "{review.rejectionReason}"
                  </p>
                </>
              )}
            </div>

            <div className="debrief-review-banner__actions">
              {review.reviewStatus === 'EDITED' && (
                <Button variant="ghost" size="sm" onClick={() => setShowDiffModal(!showDiffModal)}>
                  {showDiffModal ? 'Hide Diff' : 'View AI vs Human Diff'}
                </Button>
              )}
              <Button
                variant="secondary"
                size="sm"
                onClick={() => navigate(`/reviews/${review.id}`)}
              >
                Open Review Workspace
              </Button>
            </div>
          </div>
        )}

        {/* Side-by-Side Diff Modal / Drawer */}
        {showDiffModal && review && (
          <div className="debrief-diff-card animate-scale-in">
            <div className="debrief-diff-header">
              <h3>Side-by-Side Evaluation Comparison</h3>
              <span className="diff-note">Original AI snapshot is permanently preserved in the audit log.</span>
            </div>
            <div className="debrief-diff-grid">
              <div className="diff-col diff-col--ai">
                <h4>Original AI Evaluation</h4>
                <div className="diff-score">Score: {review.originalEvaluation.score.overall}/100</div>
                <p>"{review.originalEvaluation.summary}"</p>
              </div>
              <div className="diff-col diff-col--human">
                <h4>Human Reviewed Evaluation</h4>
                <div className="diff-score">Score: {review.finalEvaluation.score.overall}/100</div>
                <p>"{review.finalEvaluation.summary}"</p>
              </div>
            </div>
            {review.reviewerNotes && (
              <div className="diff-reviewer-notes">
                <strong>Reviewer Rationale:</strong> {review.reviewerNotes}
              </div>
            )}
          </div>
        )}

        {/* Header */}
        <div className="debrief-page__header">
          <div className="debrief-page__badge-row">
            <Badge variant="discovery">CUSTOMER DISCOVERY</Badge>
            <Badge variant={session.difficulty === 'hard' ? 'danger' : 'default'} size="sm">
              {session.difficulty.toUpperCase()}
            </Badge>
          </div>
          <h1>Conversation Debrief</h1>
          <p className="debrief-page__subtitle">
            {session.personaName} · {session.startupName || 'Your Startup'} ·{' '}
            {new Date(session.startedAt).toLocaleDateString('en-US', {
              month: 'long',
              day: 'numeric',
              year: 'numeric',
            })}{' '}
            · {Math.floor((session.durationSeconds || 60) / 60)}m{' '}
            {(session.durationSeconds || 60) % 60}s
          </p>
        </div>

        {/* Score Hero Card */}
        <Card variant="elevated" className="debrief-page__score-hero">
          <ScoreRing score={score.overall} size={130} strokeWidth={9} label="Readiness" />
          <div className="debrief-page__score-summary">
            <h2>
              {score.overall >= 80
                ? 'High-Caliber Discovery.'
                : score.overall >= 65
                ? 'Promising Foundation.'
                : score.overall >= 50
                ? 'Refinement Needed.'
                : 'Significant Methodological Gaps.'}
            </h2>
            <p>{summary}</p>
          </div>
        </Card>

        {/* Recommended Next Step Callout */}
        {recommendedNextStep && (
          <div className="debrief-recommendation-callout animate-fade-in">
            <div className="debrief-recommendation-callout__icon">
              <Zap size={20} />
            </div>
            <div>
              <h3>RECOMMENDED NEXT STEP</h3>
              <p>{recommendedNextStep}</p>
            </div>
          </div>
        )}

        {/* Metric Breakdown */}
        <Card variant="elevated" padding="lg">
          <h2 className="debrief-page__section-title">Discovery Performance Breakdown</h2>
          <div className="debrief-page__metrics">
            {score.discoveryQuality !== undefined && (
              <MetricBar label="Discovery Quality" score={score.discoveryQuality} />
            )}
            {score.questionQuality !== undefined && (
              <MetricBar label="Question Quality" score={score.questionQuality} />
            )}
            {score.listeningQuality !== undefined && (
              <MetricBar label="Listening & Empathy" score={score.listeningQuality} />
            )}
            {score.evidenceGathering !== undefined && (
              <MetricBar label="Evidence Gathering" score={score.evidenceGathering} />
            )}
            {score.goalCoverage !== undefined && (
              <MetricBar label="Assumption Coverage" score={score.goalCoverage} />
            )}
            {score.leadingQuestions !== undefined && (
              <MetricBar
                label="Leading Questions (Target: 0)"
                score={score.leadingQuestions}
                isInverse
              />
            )}
            {score.prematurePitching !== undefined && (
              <MetricBar
                label="Premature Pitches (Target: 0)"
                score={score.prematurePitching}
                isInverse
              />
            )}
          </div>
        </Card>

        {/* Strongest & Weakest Moment Highlights */}
        {(strongestMoment || weakestMoment) && (
          <div className="debrief-highlights-grid">
            {strongestMoment && (
              <div className="debrief-highlight-card debrief-highlight-card--strong">
                <div className="debrief-highlight-card__header">
                  <TrendingUp size={16} />
                  <span>STRONGEST MOMENT</span>
                </div>
                <h3>{strongestMoment.label}</h3>
                <p>{strongestMoment.description}</p>
                {strongestMoment.quote && (
                  <blockquote className="debrief-highlight-card__quote">
                    "{strongestMoment.quote}"
                  </blockquote>
                )}
              </div>
            )}

            {weakestMoment && (
              <div className="debrief-highlight-card debrief-highlight-card--weak">
                <div className="debrief-highlight-card__header">
                  <TrendingDown size={16} />
                  <span>PRIMARY IMPROVEMENT AREA</span>
                </div>
                <h3>{weakestMoment.label}</h3>
                <p>{weakestMoment.description}</p>
                {weakestMoment.quote && (
                  <blockquote className="debrief-highlight-card__quote">
                    "{weakestMoment.quote}"
                  </blockquote>
                )}
              </div>
            )}
          </div>
        )}

        {/* Detailed Leading Questions Flagged */}
        {leadingQuestionFlags.length > 0 && (
          <Card variant="elevated" className="debrief-flag-section">
            <h2 className="debrief-page__section-title">
              <AlertTriangle size={16} className="prep-icon--danger" />
              Leading Questions Flagged ({leadingQuestionFlags.length})
            </h2>
            <div className="debrief-flags-list">
              {leadingQuestionFlags.map((flag) => (
                <div key={flag.id} className="debrief-flag-card">
                  <div className="debrief-flag-card__quote">
                    <XCircle size={15} />
                    <span>Your question: "{flag.founderQuote}"</span>
                  </div>
                  <div className="debrief-flag-card__reason">{flag.issue}</div>
                  <div className="debrief-flag-card__fix">
                    <CheckCircle2 size={15} />
                    <span>{flag.betterAlternative}</span>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Premature Pitches Flagged */}
        {prematurePitchFlags.length > 0 && (
          <Card variant="elevated" className="debrief-flag-section">
            <h2 className="debrief-page__section-title">
              <AlertTriangle size={16} className="prep-icon--warning" />
              Premature Solution Pitches ({prematurePitchFlags.length})
            </h2>
            <div className="debrief-flags-list">
              {prematurePitchFlags.map((flag) => (
                <div key={flag.id} className="debrief-flag-card debrief-flag-card--pitch">
                  <div className="debrief-flag-card__quote">
                    <span>"{flag.founderQuote}"</span>
                  </div>
                  <div className="debrief-flag-card__reason">{flag.reason}</div>
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Moments: What You Did Well & What To Improve */}
        <div className="debrief-page__moments-grid">
          {/* What You Did Well */}
          <Card variant="elevated">
            <h2 className="debrief-page__section-title">
              <TrendingUp size={16} className="prep-icon--success" />
              What You Did Well
            </h2>
            <div className="debrief-page__moment-list">
              {strongMoments.map((m) => (
                <div key={m.id} className="moment-card moment-card--strong">
                  <div className="moment-card__label">{m.label}</div>
                  <p className="moment-card__desc">{m.description}</p>
                </div>
              ))}
            </div>
          </Card>

          {/* What To Improve */}
          <Card variant="elevated">
            <h2 className="debrief-page__section-title">
              <TrendingDown size={16} className="prep-icon--danger" />
              Key Areas to Improve
            </h2>
            <ul className="debrief-page__improvement-list">
              {improvements.map((imp, i) => (
                <li key={i} className="debrief-page__improvement-item">
                  <ArrowRight size={14} />
                  <span>{imp}</span>
                </li>
              ))}
            </ul>
          </Card>
        </div>

        {/* Missed Opportunities / Better Follow-Ups */}
        {missedQuestions.length > 0 && (
          <Card variant="elevated">
            <h2 className="debrief-page__section-title">
              <HelpCircle size={16} className="prep-icon--brand" />
              Missed Opportunities & Better Follow-ups
            </h2>
            <div className="debrief-page__missed-list">
              {missedQuestions.map((q) => (
                <div key={q.id} className="missed-question">
                  {q.customerStatement && (
                    <div className="missed-question__context">
                      When customer said: <em>{q.customerStatement}</em>
                    </div>
                  )}
                  <p className="missed-question__text">Better follow-up: "{q.question}"</p>
                  <p className="missed-question__why">{q.why}</p>
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Questions to Try Next Time */}
        {questionsToAsk.length > 0 && (
          <Card variant="glass">
            <h2 className="debrief-page__section-title">
              <Lightbulb size={16} className="prep-icon--brand" />
              Recommended Questions to Try Next Time
            </h2>
            <ul className="debrief-page__question-list">
              {questionsToAsk.map((q, i) => (
                <li key={i} className="debrief-page__question-item">
                  <span className="debrief-page__question-num">{i + 1}</span>
                  <span>{q}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}

        {/* Action Controls */}
        <div className="debrief-page__actions">
          <div className="debrief-page__actions-left">
            <Button
              variant="secondary"
              leftIcon={<RotateCcw size={16} />}
              onClick={() => setShowRetryModal(true)}
            >
              Practice Again
            </Button>
            <Button variant="ghost" onClick={() => navigate('/sessions')}>
              All Sessions
            </Button>
          </div>
          <Button
            variant="primary"
            glow
            rightIcon={<ArrowRight size={16} />}
            onClick={() => navigate('/dashboard')}
          >
            Back to Dashboard
          </Button>
        </div>

        {/* Retry Modal */}
        {showRetryModal && (
          <div className="debrief-modal-backdrop animate-fade-in" onClick={() => setShowRetryModal(false)}>
            <div className="debrief-modal-card animate-scale-in" onClick={(e) => e.stopPropagation()}>
              <h2>How would you like to practice?</h2>
              <p>Reinforce your discovery instincts with another simulated conversation.</p>

              <div className="debrief-modal-options">
                <button className="debrief-modal-option" onClick={handleRetrySame}>
                  <RotateCcw size={18} />
                  <div>
                    <strong>Repeat with Same Persona</strong>
                    <span>Test your corrected questioning approach against the same customer archetype.</span>
                  </div>
                </button>

                <button className="debrief-modal-option" onClick={handleSwitchPersona}>
                  <Sliders size={18} />
                  <div>
                    <strong>Choose a Different Persona</strong>
                    <span>Test yourself against a different personality (e.g. Frustrated, Polite Agree-er).</span>
                  </div>
                </button>

                <button className="debrief-modal-option" onClick={handleRetryHarder}>
                  <Zap size={18} />
                  <div>
                    <strong>Increase to Hard Difficulty</strong>
                    <span>Face unpredictable interruptions, skepticism, and evasive answers.</span>
                  </div>
                </button>
              </div>

              <div className="debrief-modal-footer">
                <Button variant="ghost" onClick={() => setShowRetryModal(false)}>
                  Cancel
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
