import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { RotateCcw, ArrowRight, TrendingUp, TrendingDown, AlertTriangle } from 'lucide-react';
import { useSessionStore } from '../../store/sessionStore';
import { useReviewStore } from '../../store/reviewStore';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { ScoreRing } from '../../components/ui/ScoreRing';
import { EmptyState } from '../../components/shared/States';
import '../discovery/DebriefPage.css';
import './PitchDebriefPage.css';

const MetricBar: React.FC<{ label: string; score: number }> = ({ label, score }) => {
  const color = score >= 80 ? 'var(--status-success)' : score >= 60 ? 'var(--brand-primary)' : score >= 40 ? 'var(--status-warning)' : 'var(--status-danger)';
  return (
    <div className="metric-bar">
      <div className="metric-bar__header">
        <span className="metric-bar__label">{label}</span>
        <span className="metric-bar__value" style={{ color }}>{score}</span>
      </div>
      <div className="metric-bar__track">
        <div className="metric-bar__fill" style={{ width: `${score}%`, background: color }} />
      </div>
    </div>
  );
};

export const PitchDebriefPage: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const { getSessionById } = useSessionStore();
  const { getReviewBySessionId } = useReviewStore();
  const [showDiffModal, setShowDiffModal] = useState(false);

  const session = id ? getSessionById(id) : undefined;
  const review = session ? getReviewBySessionId(session.id) : undefined;

  const debrief = (review && (review.reviewStatus === 'EDITED' || review.reviewStatus === 'ACCEPTED'))
    ? review.finalEvaluation
    : session?.debrief;

  if (!session || !debrief) {
    return (
      <div className="debrief-page">
        <EmptyState
          title="Session report not found"
          description="This session may not have a debrief yet."
          action={{ label: 'Back to sessions', onClick: () => navigate('/sessions') }}
        />
      </div>
    );
  }

  const { score, strongMoments, weakMoments, weakAnswers, redFlags, unansweredQuestions, improvements } = debrief;

  return (
    <div className="debrief-page">
      <div className="debrief-page__inner">
        {/* Human Review Status Banner */}
        {review && (
          <div className={`debrief-review-banner debrief-review-banner--${review.reviewStatus.toLowerCase()} animate-fade-in`}>
            <div className="debrief-review-banner__left">
              {review.reviewStatus === 'PENDING' && (
                <>
                  <Badge variant="default" size="sm">AI DIAGNOSIS — AWAITING HUMAN REVIEW</Badge>
                  <p>This report was generated by AI and is currently pending verification by a venture coach.</p>
                </>
              )}
              {review.reviewStatus === 'ACCEPTED' && (
                <>
                  <Badge variant="success" size="sm">HUMAN REVIEWED — AI EVALUATION ACCEPTED</Badge>
                  <p>Verified against transcript evidence by <strong>{review.reviewerName}</strong>.</p>
                </>
              )}
              {review.reviewStatus === 'EDITED' && (
                <>
                  <Badge variant="warning" size="sm">HUMAN REVIEWED — EVALUATION EDITED</Badge>
                  <p>
                    Original AI score was <strong>{review.originalEvaluation.score.overall}</strong>. Adjusted to <strong>{review.finalEvaluation.score.overall}</strong> by <strong>{review.reviewerName}</strong>.
                  </p>
                </>
              )}
              {review.reviewStatus === 'REJECTED' && (
                <>
                  <Badge variant="danger" size="sm">AI EVALUATION REJECTED</Badge>
                  <p>
                    Rejected by <strong>{review.reviewerName}</strong>: "{review.rejectionReason}"
                  </p>
                </>
              )}
            </div>

            <div className="debrief-review-banner__actions">
              {review.reviewStatus === 'EDITED' && (
                <Button variant="ghost" size="sm" onClick={() => setShowDiffModal(!showDiffModal)}>
                  {showDiffModal ? 'Hide Diff' : 'View AI vs Human Diff'}
                </Button>
              )}
              <Button
                variant="secondary"
                size="sm"
                onClick={() => navigate(`/reviews/${review.id}`)}
              >
                Open Review Workspace
              </Button>
            </div>
          </div>
        )}

        {/* Side-by-Side Diff Modal */}
        {showDiffModal && review && (
          <div className="debrief-diff-card animate-scale-in">
            <div className="debrief-diff-header">
              <h3>Side-by-Side Evaluation Comparison</h3>
              <span className="diff-note">Original AI snapshot is permanently preserved in the audit log.</span>
            </div>
            <div className="debrief-diff-grid">
              <div className="diff-col diff-col--ai">
                <h4>Original AI Evaluation</h4>
                <div className="diff-score">Score: {review.originalEvaluation.score.overall}/100</div>
                <p>"{review.originalEvaluation.summary}"</p>
              </div>
              <div className="diff-col diff-col--human">
                <h4>Human Reviewed Evaluation</h4>
                <div className="diff-score">Score: {review.finalEvaluation.score.overall}/100</div>
                <p>"{review.finalEvaluation.summary}"</p>
              </div>
            </div>
            {review.reviewerNotes && (
              <div className="diff-reviewer-notes">
                <strong>Reviewer Rationale:</strong> {review.reviewerNotes}
              </div>
            )}
          </div>
        )}

        <div className="debrief-page__header">
          <Badge variant="pitch">Investor Pitch</Badge>
          <h1>Pitch Debrief</h1>
          <p className="debrief-page__subtitle">{session.personaName} · {new Date(session.startedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        </div>

        <Card variant="elevated" className="debrief-page__score-hero">
          <ScoreRing score={score.overall} size={140} strokeWidth={10} label="Overall" />
          <div className="debrief-page__score-summary">
            <h2>
              {score.overall >= 80 ? 'Strong pitch.' :
               score.overall >= 65 ? 'Good foundation.' :
               score.overall >= 50 ? 'Needs more work.' : 'Significant gaps.'}
            </h2>
            <p>{debrief.summary}</p>
          </div>
        </Card>

        <Card variant="elevated" padding="lg">
          <h2 className="debrief-page__section-title">Score breakdown</h2>
          <div className="debrief-page__metrics">
            {score.pitchClarity !== undefined && <MetricBar label="Pitch Clarity" score={score.pitchClarity} />}
            {score.answerQuality !== undefined && <MetricBar label="Answer Quality" score={score.answerQuality} />}
            {score.businessUnderstanding !== undefined && <MetricBar label="Business Understanding" score={score.businessUnderstanding} />}
            {score.marketUnderstanding !== undefined && <MetricBar label="Market Understanding" score={score.marketUnderstanding} />}
            {score.tractionUnderstanding !== undefined && <MetricBar label="Traction Understanding" score={score.tractionUnderstanding} />}
            {score.objectionHandling !== undefined && <MetricBar label="Objection Handling" score={score.objectionHandling} />}
            {score.confidence !== undefined && <MetricBar label="Confidence" score={score.confidence} />}
            {score.conciseness !== undefined && <MetricBar label="Conciseness" score={score.conciseness} />}
          </div>
        </Card>

        <div className="debrief-page__moments-grid">
          <Card variant="elevated">
            <h2 className="debrief-page__section-title"><TrendingUp size={16} /> Strong moments</h2>
            {strongMoments.map(m => (
              <div key={m.id} className="moment-card moment-card--strong">
                <div className="moment-card__label">{m.label}</div>
                <p className="moment-card__desc">{m.description}</p>
              </div>
            ))}
          </Card>

          <Card variant="elevated">
            <h2 className="debrief-page__section-title"><TrendingDown size={16} /> Weak moments</h2>
            {weakMoments.map(m => (
              <div key={m.id} className="moment-card moment-card--weak">
                <div className="moment-card__label">{m.label}</div>
                <p className="moment-card__desc">{m.description}</p>
                {m.quote && <blockquote className="moment-card__quote">"{m.quote}"</blockquote>}
              </div>
            ))}
          </Card>
        </div>

        {/* Weak answers with retry */}
        {weakAnswers && weakAnswers.length > 0 && (
          <Card variant="elevated">
            <h2 className="debrief-page__section-title">Weakest answers — review and retry</h2>
            <div className="pitch-weak-answers">
              {weakAnswers.map(wa => (
                <div key={wa.id} className="weak-answer">
                  <p className="weak-answer__question">Q: {wa.investorQuestion}</p>
                  <p className="weak-answer__answer">Your answer: "{wa.founderAnswer}"</p>
                  <p className="weak-answer__feedback">{wa.feedback}</p>
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Red flags */}
        {redFlags && redFlags.length > 0 && (
          <Card variant="elevated" className="pitch-red-flags">
            <h2 className="debrief-page__section-title"><AlertTriangle size={16} /> Investor red flags</h2>
            <ul>
              {redFlags.map((f, i) => (
                <li key={i} className="pitch-red-flag-item">{f}</li>
              ))}
            </ul>
          </Card>
        )}

        {/* Unanswered questions */}
        {unansweredQuestions && unansweredQuestions.length > 0 && (
          <Card variant="glass">
            <h2 className="debrief-page__section-title">Questions you didn't answer</h2>
            <ul className="debrief-page__question-list">
              {unansweredQuestions.map((q, i) => (
                <li key={i} className="debrief-page__question-item">
                  <span className="debrief-page__question-num">{i + 1}</span>
                  <span>{q}</span>
                </li>
              ))}
            </ul>
          </Card>
        )}

        <Card variant="brand">
          <h2 className="debrief-page__section-title">How to improve next time</h2>
          <ul className="debrief-page__improvement-list">
            {improvements.map((imp, i) => (
              <li key={i} className="debrief-page__improvement-item">
                <ArrowRight size={14} />
                <span>{imp}</span>
              </li>
            ))}
          </ul>
        </Card>

        <div className="debrief-page__actions">
          <Button variant="secondary" leftIcon={<RotateCcw size={16} />} onClick={() => navigate('/pitch/new')}>
            Practice again
          </Button>
          <Button variant="primary" glow rightIcon={<ArrowRight size={16} />} onClick={() => navigate('/dashboard')}>
            Back to dashboard
          </Button>
        </div>
      </div>
    </div>
  );
};
